// <auto-generated />
using System;
using CFLv2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CFLv2.Migrations
{
    [DbContext(typeof(CFLDBContext))]
    partial class CFLDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CFLv2.Models.Schedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Attendance");

                    b.Property<int>("AwayPoints");

                    b.Property<string>("AwayTeam");

                    b.Property<DateTime>("GameDate");

                    b.Property<int>("HomePoints");

                    b.Property<string>("HomeTeam");

                    b.Property<string>("Week");

                    b.HasKey("ID");

                    b.ToTable("Schedules");

                    b.HasData(
                        new { ID = 1, Attendance = 25458, AwayPoints = 33, AwayTeam = "EDM", GameDate = new DateTime(2018, 6, 14, 19, 0, 0, 0, DateTimeKind.Unspecified), HomePoints = 30, HomeTeam = "WPG", Week = "1" },
                        new { ID = 2, Attendance = 29788, AwayPoints = 19, AwayTeam = "TOR", GameDate = new DateTime(2018, 6, 15, 19, 0, 0, 0, DateTimeKind.Unspecified), HomePoints = 27, HomeTeam = "SSK", Week = "1" },
                        new { ID = 3, Attendance = 23717, AwayPoints = 14, AwayTeam = "HAM", GameDate = new DateTime(2018, 6, 16, 19, 0, 0, 0, DateTimeKind.Unspecified), HomePoints = 28, HomeTeam = "CGY", Week = "1" },
                        new { ID = 4, Attendance = 20182, AwayPoints = 10, AwayTeam = "MTL", GameDate = new DateTime(2018, 6, 16, 19, 0, 0, 0, DateTimeKind.Unspecified), HomePoints = 22, HomeTeam = "BC", Week = "1" },
                        new { ID = 5, Attendance = 24224, AwayPoints = 17, AwayTeam = "SSK", GameDate = new DateTime(2018, 6, 21, 19, 0, 0, 0, DateTimeKind.Unspecified), HomePoints = 40, HomeTeam = "OTT", Week = "2" },
                        new { ID = 6, Attendance = 19498, AwayPoints = 56, AwayTeam = "WPG", GameDate = new DateTime(2018, 6, 22, 19, 0, 0, 0, DateTimeKind.Unspecified), HomePoints = 10, HomeTeam = "MTL", Week = "2" },
                        new { ID = 7, Attendance = 31334, AwayPoints = 38, AwayTeam = "HAM", GameDate = new DateTime(2018, 6, 22, 19, 0, 0, 0, DateTimeKind.Unspecified), HomePoints = 21, HomeTeam = "EDM", Week = "2" },
                        new { ID = 8, Attendance = 16450, AwayPoints = 41, AwayTeam = "CGY", GameDate = new DateTime(2018, 6, 23, 19, 0, 0, 0, DateTimeKind.Unspecified), HomePoints = 7, HomeTeam = "TOR", Week = "2" }
                    );
                });

            modelBuilder.Entity("CFLv2.Models.Season", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SeasonID");

                    b.Property<string>("SeasonName");

                    b.HasKey("ID");

                    b.ToTable("Seasons");

                    b.HasData(
                        new { ID = 60, SeasonID = 2018, SeasonName = "2018" }
                    );
                });

            modelBuilder.Entity("CFLv2.Models.Standing", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AwayRecord");

                    b.Property<int>("AwayWins");

                    b.Property<int>("GP");

                    b.Property<string>("HomeRecord");

                    b.Property<int>("HomeWins");

                    b.Property<string>("InDiv");

                    b.Property<string>("LongName");

                    b.Property<int>("Loses");

                    b.Property<int>("Points");

                    b.Property<int>("PointsAgainst");

                    b.Property<int>("PointsFor");

                    b.Property<int>("Rank");

                    b.Property<int>("TeamID");

                    b.Property<int>("Ties");

                    b.Property<int>("Wins");

                    b.HasKey("ID");

                    b.ToTable("Standings");

                    b.HasData(
                        new { ID = 1, AwayRecord = "", AwayWins = 0, GP = 0, HomeRecord = "", HomeWins = 0, InDiv = "", LongName = "BC Lions", Loses = 0, Points = 0, PointsAgainst = 0, PointsFor = 0, Rank = 0, TeamID = 1, Ties = 0, Wins = 0 },
                        new { ID = 2, AwayRecord = "", AwayWins = 0, GP = 0, HomeRecord = "", HomeWins = 0, InDiv = "", LongName = "Edmonton", Loses = 0, Points = 0, PointsAgainst = 0, PointsFor = 0, Rank = 0, TeamID = 2, Ties = 0, Wins = 0 },
                        new { ID = 3, AwayRecord = "", AwayWins = 0, GP = 0, HomeRecord = "", HomeWins = 0, InDiv = "", LongName = "Edmonton", Loses = 0, Points = 0, PointsAgainst = 0, PointsFor = 0, Rank = 0, TeamID = 3, Ties = 0, Wins = 0 },
                        new { ID = 4, AwayRecord = "", AwayWins = 0, GP = 0, HomeRecord = "", HomeWins = 0, InDiv = "", LongName = "Saskatchewan", Loses = 0, Points = 0, PointsAgainst = 0, PointsFor = 0, Rank = 0, TeamID = 4, Ties = 0, Wins = 0 },
                        new { ID = 5, AwayRecord = "", AwayWins = 0, GP = 0, HomeRecord = "", HomeWins = 0, InDiv = "", LongName = "Winnipeg", Loses = 0, Points = 0, PointsAgainst = 0, PointsFor = 0, Rank = 0, TeamID = 5, Ties = 0, Wins = 0 },
                        new { ID = 6, AwayRecord = "", AwayWins = 0, GP = 0, HomeRecord = "", HomeWins = 0, InDiv = "", LongName = "Toronto", Loses = 0, Points = 0, PointsAgainst = 0, PointsFor = 0, Rank = 0, TeamID = 6, Ties = 0, Wins = 0 },
                        new { ID = 7, AwayRecord = "", AwayWins = 0, GP = 0, HomeRecord = "", HomeWins = 0, InDiv = "", LongName = "Hamilton", Loses = 0, Points = 0, PointsAgainst = 0, PointsFor = 0, Rank = 0, TeamID = 7, Ties = 0, Wins = 0 },
                        new { ID = 8, AwayRecord = "", AwayWins = 0, GP = 0, HomeRecord = "", HomeWins = 0, InDiv = "", LongName = "Ottawa", Loses = 0, Points = 0, PointsAgainst = 0, PointsFor = 0, Rank = 0, TeamID = 8, Ties = 0, Wins = 0 },
                        new { ID = 9, AwayRecord = "", AwayWins = 0, GP = 0, HomeRecord = "", HomeWins = 0, InDiv = "", LongName = "Montreal", Loses = 0, Points = 0, PointsAgainst = 0, PointsFor = 0, Rank = 0, TeamID = 9, Ties = 0, Wins = 0 }
                    );
                });

            modelBuilder.Entity("CFLv2.Models.Team", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbrev");

                    b.Property<string>("City");

                    b.Property<string>("LongName");

                    b.Property<string>("Stadium");

                    b.HasKey("ID");

                    b.ToTable("Teams");

                    b.HasData(
                        new { ID = 1, Abbrev = "BC", City = "Vancouver", LongName = "BC Lions", Stadium = "BC Place" },
                        new { ID = 2, Abbrev = "EDM", City = "Edmonton", LongName = "Edmonton Eskimos", Stadium = "Commonweath Stadium" },
                        new { ID = 3, Abbrev = "CGY", City = "Calgary", LongName = "Calgary Stampeders", Stadium = "McMahon Stadium" },
                        new { ID = 4, Abbrev = "SSK", City = "Regina", LongName = "Saskatchewan Roughriders", Stadium = "Mosaic Stadium" },
                        new { ID = 5, Abbrev = "WPG", City = "Winnipeg", LongName = "Winnipeg Blue Bombers", Stadium = "Investors Group Field" },
                        new { ID = 6, Abbrev = "TOR", City = "Toronto", LongName = "Toronto Argonauts", Stadium = "BMO Field" },
                        new { ID = 7, Abbrev = "HAM", City = "Hamilton", LongName = "Hamilton Tiger-Cats", Stadium = "Tim Hortons Field" },
                        new { ID = 8, Abbrev = "OTT", City = "Ottawa", LongName = "Ottawa Redblacks", Stadium = "TD Place Stadium" },
                        new { ID = 9, Abbrev = "MTL", City = "Montreal", LongName = "Montreal Alouettes", Stadium = "Percival Molson Memorial Stadium" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
